ydlidar_ros2_driver_node:
  ros__parameters:
    port: /dev/ttyUSB0
    frame_id: laser_frame
    ignore_array: ""
    baudrate: 460800
    lidar_type: 5
    device_type: 0
    sample_rate: 4
    intensity_bit: 4
    abnormal_check_count: 3
    fixed_resolution: false
    reversion: false
    inverted: false
    auto_reconnect: true
    isSingleChannel: false
    intensity: true
    support_motor_dtr: true
    angle_max: 180.0
    angle_min: -180.0
    range_max: 20.0
    range_min: 0.025
    frequency: 250.0
    invalid_range_is_inf: false
